import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';
import { HomeIcon, UserIcon } from '@heroicons/react/24/outline';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
          <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
            {children}
          </main>

          <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
            <Link
              href="/"
              className="flex items-center gap-2 text-blue-500 hover:underline"
            >
              <HomeIcon className="h-5 w-5" />
              Home
            </Link>
            <Link
              href="/user"
              className="flex items-center gap-2 text-blue-500 hover:underline"
            >
              <UserIcon className="h-5 w-5" />
              User Info
            </Link>
          </footer>
        </div>
      </body>
    </html>
  );
}
